version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-login-project
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=1234  # Replace with a secure password
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql:/docker-entrypoint-initdb.d/setup

  redis:
    image: redis:7.0
    container_name: redis-login-project
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  oracle-data:
  redis-data: