DB_PASSWORD: 1234
MAIL_USERNAME: cjlee6009@gmail.com
MAIL_PASSWORD: rrfx iwfk xnld vivn
KAKAO_CLIENT_ID: your-kakao-client-id
KAKAO_CLIENT_SECRET: your-kakao-client-secret
JWT_SECRET_KEY: your-jwt-secret-key